import {
  FaReact,
  FaNodeJs,
  FaCss3Alt,
  FaHtml5,
  FaDocker,
  FaAws,
} from "react-icons/fa";
import {
  SiTypescript,
  SiExpress,
  SiHono,
  SiPostgresql,
  SiTailwindcss,
  SiJavascript,
  SiHiveBlockchain,
  SiPrisma,
  SiFigma,
} from "react-icons/si";
import { MdOutlineDeveloperMode } from "react-icons/md";

export const EXPLORE_LIST = [
  {
    id: 1,
    name: "React",
    description: "React is a JavaScript library for building user interfaces.",
    docs: "Build dynamic UIs with React, from components to state management and hooks.",
    icon: FaReact,
    color: "#61DAFB",
    gradient: ["from-[#61DAFB]", "to-[#0D47A1]"],
    categories: ["frontend", "javascript", "fullstack"],
  },
  {
    id: 2,
    name: "TypeScript",
    description:
      "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.",
    docs: "Enhance your JavaScript with powerful type safety for scalable apps.",
    icon: SiTypescript,
    color: "#3178C6",
    gradient: ["from-[#3178C6]", "to-[#0A66C2]"],
    categories: ["javascript", "fullstack", "backend", "frontend"],
  },
  {
    id: 3,
    name: "Node.js",
    description:
      "Node.js is a runtime environment for executing JavaScript outside the browser.",
    docs: "Backend development essentials - Express, Hono, Prisma, Authentication, and more.",
    icon: FaNodeJs,
    color: "#339933",
    gradient: ["from-[#339933]", "to-[#006400]"],
    categories: ["backend", "javascript", "fullstack"],
  },
  {
    id: 4,
    name: "Express",
    description:
      "Express is a fast, unopinionated, minimalist web framework for Node.js.",
    docs: "Middleware-driven architecture for efficient API building.",
    icon: SiExpress,
    color: "#000000",
    gradient: ["from-[#000000]", "to-[#444444]"],
    categories: ["backend", "nodejs", "fullstack"],
  },
  {
    id: 5,
    name: "Hono",
    description:
      "Hono is a high-performance web framework for the Edge and Cloud environments.",
    docs: "High-performance web framework designed for speed and scalability.",
    icon: SiHono,
    color: "#FF5733",
    gradient: ["from-[#FF5733]", "to-[#C70039]"],
    categories: ["backend", "nodejs", "fullstack"],
  },
  {
    id: 6,
    name: "PostgreSQL",
    description:
      "PostgreSQL is a powerful, open-source object-relational database system.",
    docs: "Master relational databases with advanced querying techniques.",
    icon: SiPostgresql,
    color: "#336791",
    gradient: ["from-[#336791]", "to-[#142D52]"],
    categories: ["database", "backend", "fullstack"],
  },
  {
    id: 7,
    name: "TailwindCSS",
    description:
      "TailwindCSS is a utility-first CSS framework for building custom designs quickly.",
    docs: "Rapidly build stylish interfaces with utility-first CSS.",
    icon: SiTailwindcss,
    color: "#38BDF8",
    gradient: ["from-[#38BDF8]", "to-[#1E3A8A]"],
    categories: ["frontend", "css"],
  },
  {
    id: 8,
    name: "CSS",
    description:
      "CSS is the language for describing the presentation of web pages.",
    docs: "Everything from layouts to animations and responsive designs.",
    icon: FaCss3Alt,
    color: "#1572B6",
    gradient: ["from-[#1572B6]", "to-[#0D47A1]"],
    categories: ["frontend", "css"],
  },
  {
    id: 9,
    name: "HTML",
    description: "HTML is the standard markup language for creating web pages.",
    docs: "The foundational language for building structured web pages.",
    icon: FaHtml5,
    color: "#E34F26",
    gradient: ["from-[#E34F26]", "to-[#B71C1C]"],
    categories: ["frontend", "html"],
  },
  {
    id: 10,
    name: "JavaScript",
    description: "JavaScript is a versatile programming language of the web.",
    docs: "Core language for the web - ES6+, DOM manipulation, Async operations.",
    icon: SiJavascript,
    color: "#F7DF1E",
    gradient: ["from-[#F7DF1E]", "to-[#FFD700]"],
    categories: ["frontend", "javascript", "fullstack", "backend"],
  },
  {
    id: 11,
    name: "Docker",
    description:
      "Docker is a platform for developing, shipping, and running applications in containers.",
    docs: "Learn containerization for streamlined deployments.",
    icon: FaDocker,
    color: "#2496ED",
    gradient: ["from-[#2496ED]", "to-[#0A66C2]"],
    categories: ["devops", "backend", "fullstack"],
  },
  {
    id: 12,
    name: "DevOps",
    description:
      "DevOps involves practices to automate and integrate software development processes.",
    docs: "Best practices for CI/CD, AWS, Domain Management, SSL, and DNS setup.",
    icon: MdOutlineDeveloperMode,
    color: "#0A66C2",
    gradient: ["from-[#0A66C2]", "to-[#142D52]"],
    categories: ["devops", "aws"],
  },
  {
    id: 13,
    name: "Blockchain",
    description: "Blockchain is a decentralized digital ledger technology.",
    docs: "Dive into Smart Contracts, Algorand, Solidity, and Web3 integrations.",
    icon: SiHiveBlockchain,
    color: "#121D33",
    gradient: ["from-[#121D33]", "to-[#081F2F]"],
    categories: ["blockchain", "backend"],
  },
  {
    id: 14,
    name: "Prisma",
    description: "Prisma is a next-generation ORM for Node.js and TypeScript.",
    docs: "Simplify database access with powerful query building and migrations.",
    icon: SiPrisma,
    color: "#2D3748",
    gradient: ["from-[#2D3748]", "to-[#1A202C]"],
    categories: ["database", "backend", "fullstack", "nodejs", "typescript"],
  },
  {
    id: 15,
    name: "AWS",
    description:
      "Amazon Web Services provides cloud solutions for building scalable applications.",
    docs: "Explore services like S3, CloudFront, Lambda, and more.",
    icon: FaAws,
    color: "#FF9900",
    gradient: ["from-[#FF9900]", "to-[#FF6600]"],
    categories: ["aws", "devops", "backend", "fullstack"],
  },
  {
    id: 16,
    name: "Figma",
    description:
      "Figma is a collaborative design tool for creating UI/UX prototypes and assets.",
    docs: "Learn to design visually appealing interfaces and collaborate with teams.",
    icon: SiFigma,
    color: "#F24E1E",
    gradient: ["from-[#F24E1E]", "to-[#A259FF]"],
    categories: ["design", "ui/ux"],
  },
];
